// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhJRtQ29kKabiNRIVx8g5i1i-gTRm1V2I',
    appId: '1:428775727055:web:b0918c9c365cbfe2337cba',
    messagingSenderId: '428775727055',
    projectId: 'cryptochatter-715a3',
    authDomain: 'cryptochatter-715a3.firebaseapp.com',
    storageBucket: 'cryptochatter-715a3.appspot.com',
    measurementId: 'G-Y9GVLS88DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEFfEtcQlYKpKqzDXyRry9mDeuUZloK7o',
    appId: '1:428775727055:android:ee343c1ea684b6b9337cba',
    messagingSenderId: '428775727055',
    projectId: 'cryptochatter-715a3',
    storageBucket: 'cryptochatter-715a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHuILT08BBh3am2sgQaSV3cvUSZj1RxRk',
    appId: '1:428775727055:ios:0e6cea363d039512337cba',
    messagingSenderId: '428775727055',
    projectId: 'cryptochatter-715a3',
    storageBucket: 'cryptochatter-715a3.appspot.com',
    iosClientId: '428775727055-pfglu5qfkk9qe93p2jl72ffqmc86mjv3.apps.googleusercontent.com',
    iosBundleId: 'com.cryptochatter.cryptochatter',
  );
}
